version: "3.9"
services:
  db:
    container_name: golang_pgdb
    image: postgres:14.4-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres/db/:/var/lib/postgresql/data
      # - ./postgres/logs/:/var/log/postgresql
    ports:
      - 6543:5432
    # command:
    #   [
    #     postgres,
    #     -c,
    #     log_destination=stderr,
    #     -c,
    #     logging_collector=on,
    #     -c,
    #     log_directory=/var/log/postgresql,
    #     -c,
    #     log_statement=all,
    #   ]
    networks:
      - gonetwork

  # pgadmin:
  #   container_name: golang_pgadmin_container
  #   image: dpage/pgadmin4:5.7
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: vladislav.filatov.92@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: postgres
  #     PGADMIN_CONFIG_SERVER_MODE: "False"
  #   volumes:
  #     - ./pgadmin:/var/lib/pgadmin
  #   ports:
  #     - 5051:80
  #   #    restart: unless-stopped
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.5"
  #         memory: 1G
  #   networks:
  #     - gonetwork

  app:
    container_name: golang_app
    build:
      context: .
    stop_signal: SIGKILL
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - gonetwork

networks:
  gonetwork:
    driver: bridge
